// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/hello.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_6f7617c4a1be4777, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloRespone struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRespone) Reset()         { *m = HelloRespone{} }
func (m *HelloRespone) String() string { return proto.CompactTextString(m) }
func (*HelloRespone) ProtoMessage()    {}
func (*HelloRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_hello_6f7617c4a1be4777, []int{1}
}
func (m *HelloRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRespone.Unmarshal(m, b)
}
func (m *HelloRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRespone.Marshal(b, m, deterministic)
}
func (dst *HelloRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRespone.Merge(dst, src)
}
func (m *HelloRespone) XXX_Size() int {
	return xxx_messageInfo_HelloRespone.Size(m)
}
func (m *HelloRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRespone.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRespone proto.InternalMessageInfo

func (m *HelloRespone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "wosf.hello.v1.helloRequest")
	proto.RegisterType((*HelloRespone)(nil), "wosf.hello.v1.helloRespone")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	HelloWorld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloRespone, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) HelloWorld(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloRespone, error) {
	out := new(HelloRespone)
	err := c.cc.Invoke(ctx, "/wosf.hello.v1.helloService/helloWorld", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	HelloWorld(context.Context, *HelloRequest) (*HelloRespone, error)
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_HelloWorld_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).HelloWorld(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wosf.hello.v1.helloService/HelloWorld",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).HelloWorld(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wosf.hello.v1.helloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "helloWorld",
			Handler:    _HelloService_HelloWorld_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/hello.proto",
}

func init() { proto.RegisterFile("protos/hello.proto", fileDescriptor_hello_6f7617c4a1be4777) }

var fileDescriptor_hello_6f7617c4a1be4777 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x03, 0x73, 0x84, 0x78, 0xcb, 0xf3, 0x8b,
	0xd3, 0xf4, 0x20, 0x22, 0x65, 0x86, 0x4a, 0x4a, 0x5c, 0x3c, 0x60, 0x76, 0x50, 0x6a, 0x61, 0x69,
	0x6a, 0x71, 0x89, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x67, 0x10, 0x98, 0x8d, 0xa4, 0xa6, 0xb8, 0x20, 0x3f, 0x2f, 0x15, 0x9b, 0x1a, 0xa3, 0x30, 0xa8,
	0x9a, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x37, 0x2e, 0x2e, 0x30, 0x3f, 0x3c, 0xbf,
	0x28, 0x27, 0x45, 0x48, 0x5a, 0x0f, 0xc5, 0x56, 0x3d, 0x64, 0x2b, 0xa5, 0x70, 0x48, 0x82, 0xed,
	0x72, 0x62, 0x8f, 0x62, 0x05, 0xf3, 0x93, 0xd8, 0xc0, 0xce, 0x37, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x50, 0x1c, 0xcf, 0x63, 0xd4, 0x00, 0x00, 0x00,
}
